In [3]:
# NOTE: place all these functions in a .py script and import them to save space in this ipynb
import pandas as pd
import numpy as np
from helper_functions import *

df = pd.read_csv('elo_pbp.csv')
del df['Unnamed: 0']

df['p0_name'] = [df['l_name'][i] if df['winner'][i] else df['w_name'][i] for i in xrange(len(df))]
df['p1_name'] = [df['w_name'][i] if df['winner'][i] else df['l_name'][i] for i in xrange(len(df))]
df['p0_elo'] = [df['l_elo'][i] if df['winner'][i] else df['w_elo'][i] for i in xrange(len(df))]
df['p1_elo'] = [df['w_elo'][i] if df['winner'][i] else df['l_elo'][i] for i in xrange(len(df))]
df['elo_diff'] = [df['p0_elo'][i] - df['p1_elo'][i] for i in xrange(len(df))]
df = df[['tourney_id','tourney_name','tourney_date','p0_name','p1_name','p0_elo','p1_elo','elo_diff','best_of','score','pbp','winner']]
df['tourney_name'] = [s if s==s else 'Davis Cup' for s in df['tourney_name']]
#df = df.drop(['match_num','w_elo','l_elo'],1)
df.head()

,tourney_id,tourney_name,tourney_date,p0_name,p1_name,p0_elo,p1_elo,elo_diff,best_of,score,pbp,winner
0,2010-375,Montpellier,2010-10-25,Julian Reister,Richard Gasquet,1205.868203,1389.779872,-183.911669,3,6-7 6-3 6-3,SSSS;SSSS;SSSS;SSSS;SSSS;SSSS;SSSS;SSSS;SSRRSR...,1
1,2010-375,Montpellier,2010-10-25,Romain Jouan,Taylor Dent,1201.945901,1268.518908,-66.573007,3,6-7 6-3 6-4,SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;...,1
2,2010-568,St. Petersburg,2010-10-25,Sergiy Stakhovsky,Benjamin Becker,1278.290159,1244.825382,33.464777,3,6-4 5-7 6-4,SSSS;SSSS;SSRSRRRSSS;RSRSRSRSSS;RRSSRSSRRR;SSS...,1
3,2010-568,St. Petersburg,2010-10-25,Andrey Kuznetsov,Evgeny Donskoy,1190.627927,1184.492968,6.134959,3,7-5 7-6,RSRRSSSS;SSRRSRRR;SRSRSRSRSRRR;RRRSSSSS;SSSS;S...,1
4,2010-337,Vienna,2010-10-25,Philipp Kohlschreiber,Alejandro Falla,1386.428848,1222.986734,163.442113,3,6-0 6-3,SSSS;RRRR;RSSSS;RSSRRSRSRR;SRRSSS;RRSSRR.SSRRS...,0

In [2]:
n = float(len(df))
c = 0
for i in xrange(len(df)):
    if df['p0_elo'][i] > df['p1_elo'][i]:
        c += 1
print c/n

0.54428526613

In [34]:
df_pbp = df
# add winner column and append . to end of pbp string to signify end of match if not marked
# '0' means player1 won; '1' means player2 won
df_pbp['pbp'] = [s + '.' if s[-1]!= '.' else s for s in df_pbp['pbp']]
df_pbp.rename(columns={'tourney_name':'tny_name'},inplace=True)
df_pbp.head()

,tourney_id,tny_name,tourney_date,p0_name,p1_name,p0_elo,p1_elo,elo_diff,best_of,score,pbp,winner
0,2010-375,Montpellier,2010-10-25,Julian Reister,Richard Gasquet,1205.868203,1389.779872,-183.911669,3,6-7 6-3 6-3,SSSS;SSSS;SSSS;SSSS;SSSS;SSSS;SSSS;SSSS;SSRRSR...,1
1,2010-375,Montpellier,2010-10-25,Romain Jouan,Taylor Dent,1201.945901,1268.518908,-66.573007,3,6-7 6-3 6-4,SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;...,1
2,2010-568,St. Petersburg,2010-10-25,Sergiy Stakhovsky,Benjamin Becker,1278.290159,1244.825382,33.464777,3,6-4 5-7 6-4,SSSS;SSSS;SSRSRRRSSS;RSRSRSRSSS;RRSSRSSRRR;SSS...,1
3,2010-568,St. Petersburg,2010-10-25,Andrey Kuznetsov,Evgeny Donskoy,1190.627927,1184.492968,6.134959,3,7-5 7-6,RSRRSSSS;SSRRSRRR;SRSRSRSRSRRR;RRRSSSSS;SSSS;S...,1
4,2010-337,Vienna,2010-10-25,Philipp Kohlschreiber,Alejandro Falla,1386.428848,1222.986734,163.442113,3,6-0 6-3,SSSS;RRRR;RSSSS;RSSRRSRSRR;SRRSSS;RRSSRR.SSRRS...,0

In [59]:
# split into game by game pbp strings
s = df_pbp['pbp'][1].split(';'); s_new = []
for i in range(len(s)):
    if '.' in s[i]:
        games = s[i].split('.')
        games[0] += '.'
        s_new += games
    else:
        s_new += [s[i]]

print s_new
scores = ['']
for i in range(1,len(s_new)-1):
    if s_new[i-1][-1]=='.':
        scores.append(';'.join(s_new[:i])) 
    else:
        scores.append(';'.join(s_new[:i])+';')

scores

['SSSS', 'SSSS', 'SSSS', 'SSSS', 'SSSS', 'SRRSSS', 'RRSSRSSS', 'SSSS', 'SSSS', 'SRSRSRRSSRRSSS', 'RSRSSS', 'SSSS', 'S/SS/RR/SR/SS/RR/S.', 'SSRSS', 'RRRR', 'SRSSS', 'SSSS', 'SSSRS', 'SRRSSS', 'SRSRRSSS', 'SSSS', 'RRSSSRRSRSSS.', 'SRRSRSSS', 'SRSRSS', 'SRSSS', 'RRSSSRSS', 'SRSRSS', 'SSRSS', 'RSSRSRRSRR', 'RRSSSS', 'SSRSS', 'SSRRS.', '']

['',
 'SSSS;',
 'SSSS;SSSS;',
 'SSSS;SSSS;SSSS;',
 'SSSS;SSSS;SSSS;SSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;SRSRRSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;SRSRRSSS;SSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;SRSRRSSS;SSSS;RRSSSRRSRSSS.',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;SRSRRSSS;SSSS;RRSSSRRSRSSS.;SRRSRSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;SRSRRSSS;SSSS;RRSSSRRSRSSS.;SRRSRSSS;SRSRSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;SRSRRSSS;SSSS;RRSSSRRSRSSS.;SRRSRSSS;SRSRSS;SRSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;SRSRRSSS;SSSS;RRSSSRRSRSSS.;SRRSRSSS;SRSRSS;SRSSS;RRSSSRSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;SRSRRSSS;SSSS;RRSSSRRSRSSS.;SRRSRSSS;SRSRSS;SRSSS;RRSSSRSS;SRSRSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;SRSRRSSS;SSSS;RRSSSRRSRSSS.;SRRSRSSS;SRSRSS;SRSSS;RRSSSRSS;SRSRSS;SSRSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;SRSRRSSS;SSSS;RRSSSRRSRSSS.;SRRSRSSS;SRSRSS;SRSSS;RRSSSRSS;SRSRSS;SSRSS;RSSRSRRSRR;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;SRSRRSSS;SSSS;RRSSSRRSRSSS.;SRRSRSSS;SRSRSS;SRSSS;RRSSSRSS;SRSRSS;SSRSS;RSSRSRRSRR;RRSSSS;',
 'SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;SSSS;SRSRSRRSSRRSSS;RSRSSS;SSSS;S/SS/RR/SR/SS/RR/S.;SSRSS;RRRR;SRSSS;SSSS;SSSRS;SRRSSS;SRSRRSSS;SSSS;RRSSSRRSRSSS.;SRRSRSSS;SRSRSS;SRSSS;RRSSSRSS;SRSRSS;SSRSS;RSSRSRRSRR;RRSSSS;SSRSS;']

In [8]:
from helper_functions import *
get_game_order(df_pbp['pbp'][4])

'000000.011001000.'

In [7]:
'''
patterns = ['0','00','000']
df_pbp['triples'] = [find_pattern(df_pbp['simplified_pbp'][i],'000') for i in range(len(df_pbp))]
df_pbp['doubles'] = [find_pattern(df_pbp['simplified_pbp'][i],'00') for i in range(len(df_pbp))]
df_pbp['points'] = [find_pattern(df_pbp['simplified_pbp'][i],'0') for i in range(len(df_pbp))]
'''
df_pbp['set_score'] = [get_set_score(df_pbp['pbp'][i]) for i in range(len(df_pbp))]
df_pbp['set_order'] = [get_set_order(df_pbp['pbp'][i]) for i in range(len(df_pbp))]
df_pbp['game_order'] = [get_game_order(df_pbp['pbp'][i]) for i in range(len(df_pbp))]
#df_pbp['current_game_score'] = [get_current_game_score(df_pbp['pbp'][i]) for i in range(len(df_pbp))]
#df_pbp['set_score'] = []

In [8]:
df_pbp.head(10)

,tourney_id,tny_name,tourney_date,p0_name,p1_name,p0_elo,p1_elo,elo_diff,best_of,score,pbp,winner,set_score,set_order,game_order
0,2010-375,Montpellier,2010-10-25,Julian Reister,Richard Gasquet,1205.868203,1389.779872,-183.911669,3,6-7 6-3 6-3,SSSS;SSSS;SSSS;SSSS;SSSS;SSSS;SSSS;SSSS;SSRRSR...,1,"[1, 2]","[0, 1, 1]",0101010101010.011010111.011101011.
1,2010-375,Montpellier,2010-10-25,Romain Jouan,Taylor Dent,1201.945901,1268.518908,-66.573007,3,6-7 6-3 6-4,SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;...,1,"[1, 2]","[0, 1, 1]",0101010101010.111010101.0101011101.
2,2010-568,St. Petersburg,2010-10-25,Sergiy Stakhovsky,Benjamin Becker,1278.290159,1244.825382,33.464777,3,6-4 5-7 6-4,SSSS;SSSS;SSRSRRRSSS;RSRSRSRSSS;RRSSRSSRRR;SSS...,1,"[1, 2]","[1, 0, 1]",0101110101.010101010100.0101011101.
3,2010-568,St. Petersburg,2010-10-25,Andrey Kuznetsov,Evgeny Donskoy,1190.627927,1184.492968,6.134959,3,7-5 7-6,RSRRSSSS;SSRRSRRR;SRSRSRSRSRRR;RRRSSSSS;SSSS;S...,1,"[0, 2]","[1, 1]",001101001111.0001011101011.
4,2010-337,Vienna,2010-10-25,Philipp Kohlschreiber,Alejandro Falla,1386.428848,1222.986734,163.442113,3,6-0 6-3,SSSS;RRRR;RSSSS;RSSRRSRSRR;SRRSSS;RRSSRR.SSRRS...,0,"[2, 0]","[0, 0]",000000.011001000.
5,2010-352,Paris Masters,2010-11-07,Robin Soderling,Gael Monfils,1511.122270,1452.048734,59.073536,3,6-1 7-6,RSSSS;SSRSS;RSSSS;RRRSR;SRRSSS;SSRSRRRR;RRSSSS...,0,"[2, 0]","[0, 0]",0100000.1010101010100.
6,2010-605,Tour Finals,2010-11-21,Andy Roddick,Rafael Nadal,1534.117514,1703.149562,-169.032048,3,3-6 7-6 6-4,SRRRSSSS;RRRSR;SRSSS;SSRSRRSRSS;SRSSRRRSRSSS;S...,1,"[1, 2]","[0, 1, 1]",000101010.1001101010101.0101110101.
7,2011-339,Brisbane,2011-01-02,Radek Stepanek,Tobias Kamke,1404.857661,1207.218518,197.639143,3,5-7 6-1 6-4,SSSS;SSSS;SSSS;SSSRS;RRRSR;SRSSS;SSSS;RSRSRSSR...,0,"[2, 1]","[1, 0, 0]",010111000111.0000100.1010001010.
8,2011-339,Brisbane,2011-01-02,Philipp Petzschner,Feliciano Lopez,1258.717165,1310.942182,-52.225017,3,6-4 7-6,SRSRSS;SSSRRRRSRSSS;SSSS;SRSSS;RSRRR;SSRSS;RSR...,1,"[0, 2]","[1, 1]",0101110101.1101010100011.
9,2011-339,Brisbane,2011-01-02,Benjamin Becker,Fernando Verdasco,1253.310709,1445.115131,-191.804422,3,6-1 6-7 6-3,SRRSSS;RRSSRR;SSRSRS;RSSRRR;SSRSRS;RRSSSS;RSSS...,0,"[2, 1]","[0, 1, 0]",0000010.1010101001101.000101010.

In [9]:
set(df[df['best_of']==5]['tny_name'])

{'Australian Open', 'Davis Cup', 'Roland Garros', 'US Open', 'Wimbledon'}

In [10]:
# split this df into best-of-three and best-of-five matches
#gs_tourneys = ["MensUSOpen","MensFrenchOpen",'DavisCup',"MensAustralianOpen", "GentlemensWimbledonSingles"]

#df_pbp3 = df_pbp[~df_pbp['tny_name'].isin(gs_tourneys)]
#df_pbp5 = df_pbp[df_pbp['tny_name'].isin(gs_tourneys)]
df_pbp3 = df[df['best_of']==3]
df_pbp5 = df[df['best_of']==5]
df_pbp3 = df_pbp3.reset_index(); df_pbp5 = df_pbp5.reset_index()
del df_pbp3['index']; del df_pbp5['index']

In [12]:
# interesting that it's this high for the first server in best-of-five...
#print 'player who serves first wins in best-of-three: ' + str(100*round(len(df_pbp3[df_pbp3['winner']==0])/float(len(df_pbp3)),3)) + '%'
#print 'player who serves first wins in best-of-five: ' + str(100*round(len(df_pbp5[df_pbp5['winner']==0])/float(len(df_pbp5)),3)) + '%'

In [17]:
df_pbp3.head()

,tourney_id,tny_name,tourney_date,p0_name,p1_name,p0_elo,p1_elo,elo_diff,best_of,score,pbp,winner,set_score,set_order
0,2010-375,Montpellier,2010-10-25,Julian Reister,Richard Gasquet,1205.868203,1389.779872,-183.911669,3,6-7 6-3 6-3,SSSS;SSSS;SSSS;SSSS;SSSS;SSSS;SSSS;SSSS;SSRRSR...,1,"[1, 2]","[0, 1, 1]"
1,2010-375,Montpellier,2010-10-25,Romain Jouan,Taylor Dent,1201.945901,1268.518908,-66.573007,3,6-7 6-3 6-4,SSSS;SSSS;SSSS;SSSS;SSSS;SRRSSS;RRSSRSSS;SSSS;...,1,"[1, 2]","[0, 1, 1]"
2,2010-568,St. Petersburg,2010-10-25,Sergiy Stakhovsky,Benjamin Becker,1278.290159,1244.825382,33.464777,3,6-4 5-7 6-4,SSSS;SSSS;SSRSRRRSSS;RSRSRSRSSS;RRSSRSSRRR;SSS...,1,"[1, 2]","[1, 0, 1]"
3,2010-568,St. Petersburg,2010-10-25,Andrey Kuznetsov,Evgeny Donskoy,1190.627927,1184.492968,6.134959,3,7-5 7-6,RSRRSSSS;SSRRSRRR;SRSRSRSRSRRR;RRRSSSSS;SSSS;S...,1,"[0, 2]","[1, 1]"
4,2010-337,Vienna,2010-10-25,Philipp Kohlschreiber,Alejandro Falla,1386.428848,1222.986734,163.442113,3,6-0 6-3,SSSS;RRRR;RSSSS;RSSRRSRSRR;SRRSSS;RRSSRR.SSRRS...,0,"[2, 0]","[0, 0]"

In [38]:
# DO WE NEED TO FIX THE CODE FOR CURRENT GAME SCORE??
n_samples = sum([len(a)-1 for a in df_pbp3['set_order']])
outcomes = np.zeros(n_samples); counter = 0
set_scores = [0] * n_samples
set_differentials = [0] * n_samples
#game_differentials = [0] * n_samples
elo_differentials = [0] * n_samples
for i in xrange(len(df_pbp3)):
    sets = df_pbp3['pbp'][i].split('.')
    diff = 0; set_diff = 0
    for k in xrange(len(df_pbp3['set_order'][i])-1):
        outcomes[counter] = df_pbp3['winner'][i]
        set_scores[counter] = ''.join([str(a) for a in df_pbp3['set_order'][i][:k+1]])
        score = get_current_game_score(sets[k] + ';')
        diff += score[0]; diff -= score[1]
        set_diff += (2*(df_pbp3['set_order'][i][k]==0) - 1)
        set_differentials[counter] = set_diff
        #game_differentials[counter] = diff
        elo_differentials[counter] = df_pbp3['elo_diff'][i]
        counter += 1

In [39]:
#game_differentials

In [41]:
# now, 0 means player 0 lost; 1 means player 0 won
df_sets = pd.DataFrame()
df_sets['set_scores'] = set_scores
df_sets['set_diff'] = set_differentials
df_sets['elo_diff'] = elo_differentials
df_sets['outcome'] = [1 - int(a) for a in outcomes]

In [42]:
df_sets

      set_scores  set_diff    elo_diff  outcome
0              0         1 -183.911669        0
1             01         0 -183.911669        0
2              0         1  -66.573007        0
3             01         0  -66.573007        0
4              1        -1   33.464777        0
5             10         0   33.464777        0
6              1        -1    6.134959        0
7              0         1  163.442113        1
8              0         1   59.073536        1
9              0         1 -169.032048        0
10            01         0 -169.032048        0
11             1        -1  197.639143        1
12            10         0  197.639143        1
13             1        -1  -52.225017        0
14             0         1 -191.804422        1
15            01         0 -191.804422        1
16             0         1 -144.614003        0
17            01         0 -144.614003        0
18             1        -1  -14.405015        0
19             0         1  335.357483        1
20             0         1  288.311639        1
21             1        -1   71.771269        0
22             1        -1 -175.997702        0
23             1        -1 -139.471712        0
24             0         1  141.662373        1
25             0         1   -7.781121        1
26             0         1  332.819484        1
27             0         1   40.068039        0
28            01         0   40.068039        0
29             1        -1 -290.999725        0
...          ...       ...         ...      ...
10335         10         0   40.649014        1
10336          1        -1  -74.312315        0
10337          1        -1  -27.466425        1
10338         10         0  -27.466425        1
10339          1        -1  200.024748        0
10340          0         1  -54.750287        1
10341          1        -1  -59.440463        0
10342          0         1  -20.977780        1
10343          1        -1  180.042720        1
10344         10         0  180.042720        1
10345          0         1   52.694811        1
10346          0         1  230.239472        1
10347          0         1   86.170399        0
10348         01         0   86.170399        0
10349          0         1  165.234923        1
10350          0         1 -122.957699        1
10351          1        -1    2.653439        1
10352         10         0    2.653439        1
10353          0         1  116.086432        1
10354          1        -1 -224.292341        0
10355          0         1   76.697341        1
10356          1        -1  104.297416        0
10357         10         0  104.297416        0
10358          0         1 -223.723165        1
10359         01         0 -223.723165        1
10360          0         1  -28.813345        1
10361          0         1   41.096626        1
10362         01         0   41.096626        1
10363          0         1   91.947633        1
10364         01         0   91.947633        1

[10365 rows x 4 columns]

In [135]:
# TO DO: train logistic regression just based on set scores and then on set scores + elo
# also: extend this method to game differentials and point differentials, finding a suitable
#       model which emobdies your idea of strictly increasing win probability for every won
#       point/game/set
# also: figure out why adaBoost success rate is so high...

In [71]:
from sklearn.cross_validation import train_test_split
itrain, itest = train_test_split(xrange(df_sets.shape[0]), train_size=0.7)

cols = ['set_diff']
cols = ['set_diff','elo_diff']
mask=np.ones(df_sets.shape[0], dtype='int')
mask[itrain]=1
mask[itest]=0
mask = (mask==1)

Xmatrix=df_sets[cols]
yresp=df_sets['outcome']

Xtrain=Xmatrix[mask]
Xtest=Xmatrix[~mask]
ytrain=yresp[mask]
ytest=yresp[~mask]

In [72]:
# forget this and set up a function to measure both accuracy and log_likelihood; as well as
# a pre-match prediction
def do_classify(clf, parameters, indf, featurenames, targetname, target1val, mask=None, reuse_split=None, score_func=None, n_folds=5, n_jobs=1):
    subdf=indf[featurenames]
    X=subdf.values
    y=(indf[targetname].values==target1val)*1
    if mask !=None:
        print "using mask"
        Xtrain, Xtest, ytrain, ytest = X[mask], X[~mask], y[mask], y[~mask]
    if reuse_split !=None:
        print "using reuse split"
        Xtrain, Xtest, ytrain, ytest = reuse_split['Xtrain'], reuse_split['Xtest'], reuse_split['ytrain'], reuse_split['ytest']
    if parameters:
        clf = cv_optimize(clf, parameters, Xtrain, ytrain, n_jobs=n_jobs, n_folds=n_folds, score_func=score_func)
    clf=clf.fit(Xtrain, ytrain)
    training_accuracy = clf.score(Xtrain, ytrain)
    test_accuracy = clf.score(Xtest, ytest)
    print "############# based on standard predict ################"
    print "Accuracy on training data: %0.2f" % (training_accuracy)
    print "Accuracy on test data:     %0.2f" % (test_accuracy)
    return clf, Xtrain, ytrain, Xtest, ytest

In [73]:
from sklearn import linear_model
clflogELO, Xtrain, ytrain, Xtest, ytest = do_classify(clf=linear_model.LogisticRegression(fit_intercept = True),\
                                                   parameters = None, \
                                                   indf=df_sets, featurenames=cols, targetname = 'outcome', \
                                                   target1val = 1, mask = mask)

using mask
############# based on standard predict ################
Accuracy on training data: 0.76
Accuracy on test data:     0.79

/Users/jacobgollub/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.

In [ ]:
# just confirming that winner and loser and elo's are correct
'''
import re

# read original csv file to make sure pbp and wins are correct
pbp_matches_archive = pd.read_csv("pbp_matches_atp_main_archive.csv")
pbp_matches_current = pd.read_csv("pbp_matches_atp_main_current.csv")
pbp_matches = pd.concat([pbp_matches_archive,pbp_matches_current])
pbp_matches.winner = pbp_matches.winner - 1
pbp_matches = pbp_matches.reset_index()
del pbp_matches['index']
pbp_matches['score'] = [re.sub(r"[\(\[].*?[\)\]]", "", s) for s in pbp_matches['score']]
pbp_matches['w_name'] = np.where(pbp_matches['winner'] == 0, pbp_matches['server1'], pbp_matches['server2'])
pbp_matches['l_name'] = np.where(pbp_matches['winner'] == 0, pbp_matches['server2'], pbp_matches['server1'])
pbp_matches['w_name'] = [x.replace('-',' ') for x in pbp_matches['w_name']]
pbp_matches['l_name'] = [x.replace('-',' ') for x in pbp_matches['l_name']]

match_dict = {}
for i in xrange(len(pbp_matches)):
    if pbp_matches['winner'][i]:
        s = str(pbp_matches['score'][i]) + pbp_matches['l_name'][i] + pbp_matches['w_name'][i]
    else:
        s = str(pbp_matches['score'][i]) + pbp_matches['w_name'][i] + pbp_matches['l_name'][i]
    match_dict[s] = str(pbp_matches['winner'][i])

for i in xrange(len(df)):
    if df['winner'][i]:
        s = str(df['score'][i]) + df['l_name'][i] + df['w_name'][i]
    else:
        s = str(df['score'][i]) + df['w_name'][i] + df['l_name'][i]
    if match_dict[s] != str(df['winner'][i]):
        print i'''